import {sqliteTable, text, real, integer, index, uniqueIndex} from 'drizzle-orm/sqlite-core';
export const workspaces = sqliteTable('workspaces',{id:text('id').primaryKey(),name:text('name').notNull(),tariff:real('tariff').notNull(),seeded:integer('seeded').notNull().default(0),created_at:text('created_at').notNull()});
export const sessions = sqliteTable('sessions',{token_hash:text('token_hash').primaryKey(),workspace_id:text('workspace_id').notNull().references(()=>workspaces.id),role:text('role').notNull(),tenant_id:text('tenant_id'),expires_at:integer('expires_at').notNull()},t=>[index('idx_sessions_expires').on(t.expires_at)]);
export const tenants = sqliteTable('tenants',{key:text('key').primaryKey(),workspace_id:text('workspace_id').notNull().references(()=>workspaces.id),id:text('id').notNull(),name:text('name').notNull(),floor:text('floor').notNull(),color:text('color').notNull()},t=>[uniqueIndex('idx_tenants_workspace_id').on(t.workspace_id,t.id)]);
export const meters = sqliteTable('meters',{key:text('key').primaryKey(),workspace_id:text('workspace_id').notNull().references(()=>workspaces.id),id:text('id').notNull(),name:text('name').notNull(),tenant_id:text('tenant_id').notNull(),location:text('location').notNull(),threshold_kwh:real('threshold_kwh').notNull(),interval_minutes:integer('interval_minutes').notNull()},t=>[uniqueIndex('idx_meters_workspace_id').on(t.workspace_id,t.id)]);
export const readings = sqliteTable('readings',{id:text('id').primaryKey(),workspace_id:text('workspace_id').notNull().references(()=>workspaces.id),meter_id:text('meter_id').notNull(),recorded_at:text('recorded_at').notNull(),consumption_kwh:real('consumption_kwh').notNull()},t=>[uniqueIndex('idx_readings_meter_timestamp').on(t.workspace_id,t.meter_id,t.recorded_at),index('idx_readings_workspace_time').on(t.workspace_id,t.recorded_at)]);
export const alerts = sqliteTable('alerts',{id:text('id').primaryKey(),workspace_id:text('workspace_id').notNull().references(()=>workspaces.id),meter_id:text('meter_id').notNull(),type:text('type').notNull(),title:text('title').notNull(),detail:text('detail').notNull(),severity:text('severity').notNull(),status:text('status').notNull(),recorded_at:text('recorded_at').notNull()},t=>[index('idx_alerts_workspace_meter').on(t.workspace_id,t.meter_id)]);
export const notes = sqliteTable('notes',{id:text('id').primaryKey(),workspace_id:text('workspace_id').notNull().references(()=>workspaces.id),alert_id:text('alert_id').notNull().references(()=>alerts.id),body:text('body').notNull(),author:text('author').notNull(),created_at:text('created_at').notNull()},t=>[index('idx_notes_alert').on(t.alert_id)]);
export const imports = sqliteTable('imports',{id:text('id').primaryKey(),workspace_id:text('workspace_id').notNull().references(()=>workspaces.id),file_name:text('file_name').notNull(),accepted:integer('accepted').notNull(),skipped:integer('skipped').notNull(),rejected:integer('rejected').notNull(),created_at:text('created_at').notNull()},t=>[index('idx_imports_workspace').on(t.workspace_id)]);
